name: dayutianfei
description: Winter is coming... 

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: http://dayutianfei.github.io
permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: dayutianfei
    disqus_shortname: #

ga_id: #
ga_username: #

timezone: Asia/Shanghai
